version: '3.9'

services:
  mongo:
    image: mongo:4
    ports:
      - 27018:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      timeout: 10s
      retries: 10
